Release ФЗ9. Добавлен сервер и обработчики. Добавлены новые и отредактированы старые тесты
andrey1455-ya/java-kanban pull request #4
Opened 2024-12-14 18:06 UTC by andrey1455-ya

…тированы старые тесты

2024-12-15 23:40 UTC, vlolad requested changes
Привет!

По тестам отлично, по новому функционалу тоже. В новый год без долгов)
Две небольшие доработки:

1) main метод, как точка входа, не должна выбрасывать никаких исключений. Там их желательно все отлавливать или каким-либо иным образом обрабатывать. Тут она вообще не особо используется т.к. код покрыт тестами, но всё же
Не обязательно, но желательно убрать

2) В хендлерах много if-else блоков с повторяющимися условиями, их лучше сократить

В остальном - отлично, по коду дополнений нет)
Хорошего дня!

2024-12-15 23:40 UTC, vlolad commented on src/Main.java
> +    public static void main(String[] args) throws NotFoundException {
В main лучше уж ничего не выбрасывать)

2024-12-15 23:40 UTC, vlolad commented on src/server/EpicHandler.java
> +public class EpicHandler extends BaseHttpHandler {
Хорошо, что разделил хендлеры по типам задач. Частая ошибка, когда пытаются уместить всю обработку в один

2024-12-15 23:40 UTC, vlolad commented on src/server/EpicHandler.java
> +            if ("GET".equals(method) && path.equals("/epics")) {
`"GET".equals(method)` повторяется, можно оптимизировать ветвление

P.S. идеально со siwtch-case

2024-12-15 23:40 UTC, vlolad commented on src/server/SubtaskHandler.java
> +            if ("GET".equals(method) && path.equals("/subtasks/")) {
Тут аналогично можно упростить ветвление

2024-12-15 23:40 UTC, vlolad commented on src/server/TaskHandler.java
> +            if ("GET".equals(method) && path.matches("/tasks/\\d+")) {
И тут тоже упростить)

2024-12-16 08:42 UTC, andrey1455-ya commented on src/Main.java
> +    public static void main(String[] args) throws NotFoundException {
Вообще удалил Main как неиспользуемый)

2024-12-16 08:42 UTC, andrey1455-ya commented on src/server/EpicHandler.java
> +            if ("GET".equals(method) && path.equals("/epics")) {
Переписал

2024-12-16 08:42 UTC, andrey1455-ya commented on src/server/SubtaskHandler.java
> +            if ("GET".equals(method) && path.equals("/subtasks/")) {
и тут тоже)

2024-12-16 08:43 UTC, andrey1455-ya commented on src/server/TaskHandler.java
> +            if ("GET".equals(method) && path.matches("/tasks/\\d+")) {
И тут)

2024-12-16 21:57 UTC, vlolad approved these changes
Привет!

Принято

2024-12-17 09:59 UTC, merged